config/routes.rb
Comptracker::Application.routes.draw do
  resources :comps

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :accounts, only: [:new, :create, :destroy]
  
  root "static_pages#home"

  get "users/:id/get_total_rewards_comps", to: "users#get_total_rewards_comps"
  get "users/:id/get_borgata_comps", to: "users#get_borgata_comps"
  match "users/:id/send_comps_email", to: "users#send_comps_email", via: "post"
  
  match "/signup", to: "users#new", via: "get"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  match "/help", to: "static_pages#help", via: "get"

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      flash[:error] = "Already signed in. Sign out first to sign in as a different user."
      redirect_to(current_user)
    end
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Comptracker</h1>
  <h4>Casinos take enough of your money. Never miss a comp.</h4>
  
  <%= link_to "Sign Up", signup_path, class: "btn"%> or <%= link_to "Sign In", signin_path, class: "btn" %>
  
  <!-- <%= link_to "Help", help_path %> -->
</div>