config/routes.rb
Comptracker::Application.routes.draw do
  resources :comps

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :accounts, only: [:new, :create, :destroy]
  
  root "static_pages#home"

  get "users/:id/get_total_rewards_comps", to: "users#get_total_rewards_comps"
  get "users/:id/get_borgata_comps", to: "users#get_borgata_comps"
  match "users/:id/send_comps_email", to: "users#send_comps_email", via: "post"
  
  match "/signup", to: "users#new", via: "get"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  match "/help", to: "static_pages#help", via: "get"

  

end

app/models/comp.rb
class Comp < ActiveRecord::Base
  belongs_to :account
  
  validates :expiration, presence: true
end

app/controllers/comps_controller.rb
class CompsController < ApplicationController
  before_action :set_comp, only: [:show, :edit, :update, :destroy]

  # GET /comps
  # GET /comps.json
  def index
    @comps = Comp.all
  end

  # GET /comps/1
  # GET /comps/1.json
  def show
  end

  # GET /comps/new
  def new
    @comp = Comp.new
  end

  # GET /comps/1/edit
  def edit
  end

  # POST /comps
  # POST /comps.json
  def create
    @comp = Comp.new(comp_params)

    respond_to do |format|
      if @comp.save
        format.html { redirect_to @comp, notice: 'Comp was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comp }
      else
        format.html { render action: 'new' }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comps/1
  # PATCH/PUT /comps/1.json
  def update
  end

  # DELETE /comps/1
  # DELETE /comps/1.json
  def destroy
    @comp.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comp
      @comp = Comp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comp_params
      params.require(:comp).permit(:user_id, :account_id, :description, :expiration, :days_until_expiration)
    end
    
    
end

app/helpers/comps_helper.rb
module CompsHelper
end

app/views/comps/_form.html.erb
<%= form_for(@comp) do |f| %>
  <% if @comp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comp.errors.count, "error") %> prohibited this comp from being saved:</h2>

      <ul>
      <% @comp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :expiration %><br>
    <%= f.text_field :expiration %>
  </div>
  <div class="field">
    <%= f.label :days_until_expiration %><br>
    <%= f.text_field :days_until_expiration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comps/edit.html.erb
<h1>Editing comp</h1>

<%= render 'form' %>

<%= link_to 'Show', @comp %> |
<%= link_to 'Back', comps_path %>

app/views/comps/index.html.erb
<h1>Listing comps</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Account</th>
      <th>Description</th>
      <th>Expiration</th>
      <th>Days until expiration</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comps.each do |comp| %>
      <tr>
        <td><%= comp.user_id %></td>
        <td><%= comp.account_id %></td>
        <td><%= comp.description %></td>
        <td><%= comp.expiration %></td>
        <td><%= comp.days_until_expiration %></td>
        <td><%= link_to 'Show', comp %></td>
        <td><%= link_to 'Edit', edit_comp_path(comp) %></td>
        <td><%= link_to 'Destroy', comp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comp', new_comp_path %>

app/views/comps/new.html.erb
<h1>New comp</h1>

<%= render 'form' %>

<%= link_to 'Back', comps_path %>

app/views/comps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comp.user_id %>
</p>

<p>
  <strong>Account:</strong>
  <%= @comp.account_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comp.description %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @comp.expiration %>
</p>

<p>
  <strong>Days until expiration:</strong>
  <%= @comp.days_until_expiration %>
</p>

<%= link_to 'Edit', edit_comp_path(@comp) %> |
<%= link_to 'Back', comps_path %>