config/routes.rb
Comptracker::Application.routes.draw do
  resources :comps

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :accounts, only: [:new, :create, :destroy]
  
  root "static_pages#home"

  get "users/:id/get_total_rewards_comps", to: "users#get_total_rewards_comps"
  get "users/:id/get_borgata_comps", to: "users#get_borgata_comps"
  match "users/:id/send_comps_email", to: "users#send_comps_email", via: "post"
  
  match "/signup", to: "users#new", via: "get"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  match "/help", to: "static_pages#help", via: "get"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :accounts, dependent: :destroy
  has_many :comps, :through => :accounts
  before_save { email.downcase! }
  before_create :create_remember_token
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  private
  
      def create_remember_token
        self.remember_token = User.encrypt(User.new_remember_token)
      end

end

app/controllers/users_controller.rb
require 'watir-webdriver'
require 'date'
require 'time'

class UsersController < ApplicationController
  before_action :signed_in_user, only: :show
  before_action :correct_user, only: :show
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @accounts = @user.accounts
    
    # if @accounts.count > 0
    # 
    #   # scrape Total Rewards if the user has entered a Total Rewards Account
    #   if @accounts.find_by(:type_of_account => "Total Rewards")
    #     get_total_rewards_comps
    #   end
    #   
    #   # scrape Borgata Rewards
    #   if @accounts.find_by(:type_of_account => "Borgata Rewards")
    #     get_borgata_comps
    #   end
    # end
    
  end

  def get_total_rewards_comps
    @user = User.find(params[:id])
    @accounts = @user.accounts
    # set up and initialize Watir and Phantomjs in a way that works for the Total Rewards Page.
    capabilities = Selenium::WebDriver::Remote::Capabilities.phantomjs("phantomjs.page.settings.userAgent" => "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36")
    driver = Selenium::WebDriver.for :phantomjs, :desired_capabilities => capabilities
    switches = ['--ignore-ssl-errors=yes']
    browser = ::Watir::Browser.new driver 

    
    total_rewards_account = @accounts.find_by(:type_of_account => "Total Rewards")

    # get to offers page
    browser.goto  "http://www.totalrewards.com/e-totalrewards/?"
    browser.input(:id => "username").to_subtype.set(total_rewards_account.username)
    browser.input(:id => "pin").to_subtype.set(total_rewards_account.password_digest)
    browser.button(:value => "Sign In").click
    browser.link(:href => "/TotalRewards/Offers.do?", :text => "Your Offers").click
    
    # scrape offers
    browser.frame(:id => "offerDisplayMod_iframe").wait_until_present
    offers = browser.frame(:id => "offerDisplayMod_iframe").divs(:class => "pItem")
    @total_rewards_comps = {}
    offers.each do |offer|
      if offer.span(:class => "lblSubjectOld").exists?
        name = offer.span(:class => "lblSubjectOld").text
      else
        name = offer.span(:class => "lblSub").text
      end
      date = offer.div(:class => "expwidth").text
      
      @total_rewards_comps[name] = date
    end
    
    @total_rewards_comps.each do |key, value|
      value.chomp!
      expiration = value[-10..-1]
      expiration = DateTime.strptime(expiration, '%m/%d/%Y')
      today = Date.today
      @total_rewards_comps[key] = expiration.mjd - today.mjd
    end
    
    browser.close
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def get_borgata_comps
    @user = User.find(params[:id])
    @accounts = @user.accounts
    
    # Check and wait until watir / phantomjs is done with other requests
    browsers = []
    ObjectSpace.each_object(Watir::Browser) {|b| browsers << b}
    p browsers
    p browsers.any? {|b| b.exists?}
    Watir::Wait.until { (browsers.any? {|b| b.exists?}) == false }
    
    # set up and initialize Watir and Phantomjs in a way that works for the Borgata page.
    switches = ['--ignore-ssl-errors=yes']
    browser = Watir::Browser.new :phantomjs, :args => switches
    
    # get to offers page
    borgata_account = @accounts.find_by(:type_of_account => "Borgata Rewards")
    browser.goto "https://www.theborgata.com/casino/mbr"
    browser.input(:id => "borgataMainContentWrapped_content_0_ctlLoginForm_txtEmailAddressOrAccountNumber").to_subtype.set(borgata_account.username)
    browser.input(:id => "borgataMainContentWrapped_content_0_ctlLoginForm_txtPassword").to_subtype.set(borgata_account.password_digest)
    browser.link(:id => "borgataMainContentWrapped_content_0_ctlLoginForm_btnLogin").click
    
    # scrape comps
    comps = browser.table(:class => "data-list-table offers").tbody.trs
    @borgata_comps = {}
    
    comps.each do |comp|
      name = comp.td(:class => "offer-name").text
      date = comp.td(:class => "offer-date").text
      
      date.chomp!
      expiration = date[-8..-1]
      expiration.lstrip!
      expiration = Date.strptime(expiration, '%m.%d.%y')
      
      today = Date.today
      
      @borgata_comps[name] = expiration.mjd - today.mjd
    end
  
    browser.close 
    
    respond_to do |format|
      format.js
    end
  end
  

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.welcome_email(@user).deliver
      
      sign_in @user
      
      redirect_to @user, notice: 'User was successfully created.'
    else
      render 'new'
    end
    
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    cookies.delete(:remember_token)
    redirect_to root_url
  end
  
  def send_comps_email
    @user = User.find(params[:id])
    UserMailer.comp_email(@user).deliver
    redirect_to @user
  end
  
  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        redirect_to signin_url
      end
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

 
  
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  

<% end %>

  <p> Already have an account? <%= link_to "Sign in", signin_path %> </p>

app/views/users/_get_borgata_comps.html.erb
<% @borgata_comps.each do |key, value| %> 
	<div>
		<%= "#{key}  :: Expires in #{value} days." %>
	</div>
<% end %>

app/views/users/_get_total_rewards_comps.html.erb
<% @total_rewards_comps.each do |key, value| %> 
	<div>
		<%= "#{key}  :: Expires in #{value} days." %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/get_borgata_comps.js.erb
$("#borgatacomps").html("<%= escape_javascript(render('get_borgata_comps')) %>")

app/views/users/get_total_rewards_comps.html.erb
<% @total_rewards_comps.each do |key, value| %> 
	<div>
		<%= "#{key}  :: Expires in #{value} days." %>
	</div>
<% end %>	

app/views/users/get_total_rewards_comps.js.erb
$("#totalrewardscomps").html("<%= escape_javascript(render('get_total_rewards_comps')) %>")

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
		<th>ID</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
		<td><%= user.id %></td>
        <td><%= user.email %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, :method=>:delete, class: :destroy, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p> <%= flash[:error] %> </p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p> ---- </p>

<p>
	<strong>Accounts You've Registered:</strong>
</p>


<% if @accounts.empty? %>
  <p>
    <%= "No accounts yet. Add some!" %>
  </p>
<% else %>
  <% @accounts.each do |account| %>
     <p> <%= account.type_of_account%>  ::
		 Username: <%= account.username %>  ::
	     Password: <%= account.password_digest%>  :: 
	 	 <%= link_to '<< Delete this account', account, :method=>:delete, :class=>:destroy, data: {confirm: "Delete this account?"} %></p>
  <% end %>
<% end %>

<p> <%= link_to 'Add casino account', new_account_path %> </p>

<p> ---- </p>

<% if @accounts.any? {|account| account.type_of_account == "Total Rewards"}%>
	<div>
		<strong>Comps available at Harrah's, Bally's, Caesars, or Showboat:</strong> 
	</div>
	<div id="totalrewardscomps">
		<div id="loadicon"><%= image_tag("loader.gif")%></div>
		<%= link_to "", "#{@user.id}/get_total_rewards_comps", :remote=> true, id: "load_total_rewards" %>
	    </div>
<%end%>

<% if @accounts.any? {|account| account.type_of_account == "Borgata Rewards"} %>
	<div>
		<strong>Comps available at Borgata:</strong> 
	</div>
	<div id="borgatacomps">
	<div id="loadicon"><%= image_tag("loader.gif")%></div>
	<%= link_to "", "#{@user.id}/get_borgata_comps", :remote=> true, id: "load_borgata_comps" %>
    </div>
<%end%>

<%= link_to "send comp email", "#{@user.id}/send_comps_email", :method=>:post%>

<p> ---- </p>

<p> <%= link_to 'Sign out', signout_path, method: "delete" %>
<p> <%= link_to 'Delete my account', current_user, :method=>:delete, :class=>:destroy, data: {confirm: "Are you sure?"} %>
 </p>

 <script>
 
 $(document).ready(function(){ $('a#load_total_rewards').first().click(); });
 $(document).ready(function(){ $('a#load_borgata_comps').first().click(); });


 
 </script